### ISSUE TITLE
Kagura

### ISSUE THREAD

**Issue by ghost** [sonyxperiadev/kernel#2281]
make aosp_tone_kagura_defconfig                     HOSTCC  scripts/basic/bin2c
backports/compat/Kconfig:57: warning: ignoring unknown option bp_modules#
# configuration written to .config
#
siswa@siswa:~/kernel$ make -j$(nproc --all)                             arch/arm64/Makefile:67: *** CROSS_COMPILE_ARM32 not defined or empty, the compat vDSO will not be built.  Stop.

**Comment by ix5** [comment]
Please use the [issue tracker](https://github.com/sonyxperiadev/bug_tracker/issues/) for reporting any issues.

There, you will also be directed to fill out a form with more information. As it stands, we sadly cannot help you with your issue because we can only guess which configuration you are using to build.

**Comment by danascape** [comment]
export cross compile 32 path to the arm toolchain

**Comment by erwinabs** [comment]
Oke sir thanks you

**Comment by Haxk20** [comment]
@jerpelea Please close this
